services:
  coraza:
    build:
      context: corazaaccess/
      dockerfile: Dockerfile
  nginx:
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
    depends_on:
      - coraza
      - backend
  backend:
    image: vulnerables/web-dvwa
